### ISSUE TITLE
error: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by akritaag** [dat/pyner#10]
Hey I implemented the following code:

```
tagger = ner.HttpNER(host='localhost', port=8080)
a = "Kate Walsh, on the cover of More magazine's April issue, appears on The Ellen DeGeneres Show. More magazine Kate Walsh on The Ellen DeGeneres Show 4/14/11"

tagger.get_entities(a)
```

but I am getting a connection refused error. 

```
Traceback (most recent call last):
  File "/Volumes/Privet Drive/Copy/University of Cincinnati/intern/FEM R&D/parse.py", line 16, in <module>
    tagger.get_entities(a)
  File "build/bdist.macosx-10.9-intel/egg/ner/client.py", line 81, in get_entities
    tagged_text = self.tag_text(text)
  File "build/bdist.macosx-10.9-intel/egg/ner/client.py", line 165, in tag_text
    c.request('POST', self.location, params, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 61] Connection refused
```

Can somebody please point out where I might be going wrong?

**Comment by dat** [comment]
This is only the Python client. You need to deploy and run this also as a server that you can connect to: https://github.com/dat/stanford-ner

Look into deploying the stanford-ner as a .war file on Apache Tomcat server.

**Comment by akritaag** [comment]
Worked! Thank you dat :+1:
